# Generated by Django 4.0.1 on 2022-03-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madbankapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructioninvestment',
            name='timestamp',
            field=models.DateField(verbose_name='investment date'),
        ),
        migrations.AlterField(
            model_name='parentallowance',
            name='timestamp',
            field=models.DateField(verbose_name='allowance date'),
        ),
    ]
