# Generated by Django 4.0.1 on 2022-03-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madbankapp', '0002_alter_constructioninvestment_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructioninvestment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='parentallowance',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
