# Generated by Django 4.0.1 on 2022-03-30 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madbankapp', '0003_alter_constructioninvestment_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymembers',
            options={'verbose_name_plural': 'familymembers'},
        ),
    ]
