# Generated by Django 4.0.1 on 2022-03-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madbankapp', '0005_rename_person_parentallowance_familymembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionproject',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
