# Generated by Django 4.0.1 on 2022-03-30 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madbankapp', '0007_rename_contribution_parentallowance_allowance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentallowance',
            old_name='familymember',
            new_name='fam_member',
        ),
    ]
