# Generated by Django 4.0.1 on 2022-04-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madbankapp', '0009_familymembers_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentallowance',
            options={'ordering': ['-timestamp']},
        ),
    ]
