# Generated by Django 4.0.1 on 2022-04-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madbankapp', '0010_alter_parentallowance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentallowance',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
