# Generated by Django 4.0.1 on 2022-04-10 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madbankapp', '0012_alter_parentallowance_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactiontracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madbankapp.parentallowance')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madbankapp.constructioninvestment')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madbankapp.familymembers')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madbankapp.constructionproject')),
            ],
        ),
    ]
