# Generated by Django 4.0.1 on 2022-04-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madbankapp', '0013_transactiontracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='transactiontracker',
        ),
    ]
