# Generated by Django 4.0.1 on 2022-04-17 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madbankapp', '0014_delete_transactiontracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructioninvestment',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='constructionPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madbankapp.constructionproject')),
            ],
        ),
    ]
