# Generated by Django 4.0.1 on 2022-04-17 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madbankapp', '0015_alter_constructioninvestment_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionphotos',
            name='phase',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='madbankapp.constructionproject'),
        ),
    ]
